(function(){
var Q=document;function T(){var c=Q.cookie,a=Math.round((new Date).getTime()/1000),b=c.indexOf("__utma=")>-1,d=c.indexOf("__utmb=")>-1,e=c.indexOf("__utmc=")>-1,f,g={};if(b){f=c.split("__utma=")[1].split(";")[0].split(".");g.sid=(!d||!e?a:f[4])+"";g.vid=f[1]+"."+f[2];g.from_cookie=true}else{g.sid=window&&window.gaGlobal&&window.gaGlobal.sid?window.gaGlobal.sid:a+"";g.vid=window&&window.gaGlobal&&window.gaGlobal.vid?window.gaGlobal.vid:Math.round(Math.random()*2147483647)+"."+a;g.from_cookie=false}g.hid=
window&&window.gaGlobal&&window.gaGlobal.hid?window.gaGlobal.hid:Math.round(Math.random()*2147483647);window.gaGlobal=g;return g}(function(){function c(){}c.prototype.l=function(d){var e=d.indexOf("#")+1;return e?d.substr(e):""};c.prototype.n=function(d){return/[&<>\"]/.test(d)?d.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"):d};c.prototype.b=function(d){var e="<iframe";for(var f in d){e+=" "+f+'="'+this.n(d[f])+'"'}return e+"></iframe>"};c.prototype.m=function(d,
e){try{return d.frames[e]}catch(f){return null}};c.prototype.e=function(d){var e=document.createElement("iframe");for(var f in d){e.setAttribute(f,d[f])}return e};c.prototype.i=function(d,e){var f=this;document.body.appendChild(f.e({id:d,name:d,src:e,width:0,height:0,frameBorder:0}))};c.prototype.s=function(d,e){var f=this;document.write(f.b({id:d,name:d,src:e,width:0,height:0,frameBorder:0}))};c.prototype.g=function(d,e){var f=[],g=d.length,i=0;while(i<g){var m=d.substr(i,e),j=m.length;if(i+j<g){for(var l=
1;l<3;++l){if(m.charAt(j-l)=="%"){m=m.substr(0,j-=l)}}}f.push(m);i+=j}return f};c.prototype.a=function(d,e,f){if(!window[d]){var g=window[d]=new e;for(var i=0;i<f.length;++i){g[f[i][0]]=f[i][1]}}};var a=c.prototype,b=[["getHash",a.l],["htmlEscape",a.n],["makeIframeTag",a.b],["getIframe",a.m],["makeIframeNode",a.e],["appendHiddenIframe",a.i],["writeHiddenIframe",a.s],["splitURIComponent",a.g],["exportSingleton",a.a],["MAX_URL_LENGTH",4095],["IDI_DEFAULT_POLLING_INTERVAL",1000]];c.prototype.a("IDICommon",
c,b)})();(function(){function c(e,f){for(var g in f){e[g]=f[g]}}function a(){var e=this;e.t=window.location.href.replace(/([^:\/])\/.*$/,"$1/robots.txt");e.u="";e.k={};e.c={};e.f={};e.v={};e.o={}}a.prototype.x=function(e,f){var g=this,i=g.c[e];if(isNaN(i)){throw new Error("Invalid module id");}else{var m=g.d(g.v[e]),j=encodeURIComponent(f)+"$",l=IDICommon.MAX_URL_LENGTH-1-m.length,k=IDICommon.g(j,l),o=k.length;for(var p=0;p<o;++p){IDICommon.i(e+"_"+(i+p),m+"#"+k[p])}g.c[e]+=o}};a.prototype.p=function(e,
f,g){var i=this;i.h(e);i.o[e]=window.setInterval(function(){i.w(e,f)},typeof g=="object"&&g.pollingInterval||IDICommon.IDI_DEFAULT_POLLING_INTERVAL)};a.prototype.h=function(e){var f=this;window.clearInterval(f.o[e]);f.o[e]=0};a.prototype.q=function(e){this.t=e};a.prototype.r=function(e){this.u=e};a.prototype.d=function(e){return this.u||e.replace(/([^:\/]\/).*$/,"$1ig/idi_relay")};a.prototype.w=function(e,f){var g=this,i=window.frames[e];if(i){var m;while(m=IDICommon.m(i,e+"_"+g.k[e])){try{if(m.location.href==
"about:blank"){break}}catch(j){break}g.f[e]+=IDICommon.l(m.location.href);++g.k[e]}var l=g.f[e].split("$"),k=l.length-1;if(k>0){g.f[e]=l[k];for(var o=0;o<k;++o){f(decodeURIComponent(l[o]),e)}}}};a.prototype.j=function(e,f,g,i,m){var j=this,l={frameBorder:0,scrolling:"no"},k,o,p,z,s;if(typeof m=="object"){k=m.iframeAttrs;o=m.callback;p=m.userPrefs;z=m.pollingInterval;s=m.parentDivId}if(typeof k=="object"){c(l,k)}c(l,{id:f,name:f,src:e,width:g,height:i});j.k[f]=0;j.c[f]=0;j.f[f]="";j.v[f]=e;var t=[];
if(typeof p=="object"){for(var q in p){t.push(encodeURIComponent(q)+"="+encodeURIComponent(p[q]))}}if(typeof o=="function"){t.push("idi_hr="+encodeURIComponent(j.t));j.p(f,o,m)}if(t.length){var r=t.join("&");if(l.src.length+1+r.length>IDICommon.MAX_URL_LENGTH){r+="$";var w=j.d(e),A=IDICommon.MAX_URL_LENGTH-1-w.length,H=IDICommon.g(r,A),I=H.length;for(var q=0;q<I;++q){var E=f+"_"+q,J=w+"#"+H[q];if(s){var x=document.getElementById(s);x.innerHTML=x.innerHTML+j.e({id:E,name:E,src:J,width:0,height:0,frameBorder:0})}else{IDICommon.s(E,
J)}}j.c[f]+=I;r=""}l.src+="#"+r}if(s){var x=document.getElementById(s);x.innerHTML=x.innerHTML+IDICommon.b(l)}else{document.write(IDICommon.b(l))}};var b=a.prototype,d=[["setHostRelayUrl",b.q],["setModuleRelayUrl",b.r],["getModuleRelayUrl",b.d],["createModule",b.j],["postMessageToModule",b.x],["registerListener",b.p],["unregisterListener",b.h]];IDICommon.a("IDIHost",a,d)})();function u(c){return c!=null?'"'+c+'"':'""'}function R(c){if(typeof encodeURIComponent=="function"){return encodeURIComponent(c)}else{return escape(c)}}
function h(c,a){if(a){window.google_ad_url+="&"+c+"="+a}}function n(c,a){if(a){h(c,R(a))}}function v(c,a,b){if(a&&typeof a=="object"){a=a[b%a.length]}h("color_"+c,a)}function V(c,a){var b=c.screen,d=navigator.javaEnabled(),e=-a.getTimezoneOffset();if(b){h("u_h",b.height);h("u_w",b.width);h("u_ah",b.availHeight);h("u_aw",b.availWidth);h("u_cd",b.colorDepth)}h("u_tz",e);h("u_his",history.length);h("u_java",d);if(navigator.plugins){h("u_nplug",navigator.plugins.length)}if(navigator.mimeTypes){h("u_nmime",
navigator.mimeTypes.length)}}function B(c){if(c){c=c.toLowerCase();if(c.substring(0,3)!="ca-"){c="ca-"+c}}return c}function fa(c,a){var b=document.getElementById(c);b.style.height=a+"px"}function W(c,a,b){window.clearTimeout(b);var d=/^google_resize_flash_ad_idi\((\d+)\)/,e=c.match(d);if(e){fa(a,e[1])}}function ha(c,a,b,d){b=b.substring(0,2000);b=b.replace(/%\w?$/,"");if(c.google_ad_output=="js"&&(c.google_ad_request_done||c.google_radlink_request_done)){a.write('<script language="JavaScript1.1" src='+
u(b)+"><\/script>")}else if(c.google_ad_output=="html"){if(c.name!="google_ads_frame"){if(d!=null){a.write('<div id="'+d+'">')}if(Y(c.google_ad_output,c.google_ad_client)){if(c.google_relay){IDIHost.q(c.google_relay)}IDIHost.r("http://pagead2.googlesyndication.com/pagead/idi_relay.html");var e="google_inline_div"+c.google_num_ad_slots,f="<div id="+u(e)+' style="position:relative;"></div><div style="position:relative;width:'+c.google_ad_width+"px;height:"+c.google_ad_height+'px;z-index:-1"></div>';
a.write(f);var g="google_frame"+c.google_num_ad_slots,i=c.setTimeout(function(){IDIHost.h(g)},5000);IDIHost.j(b,g,c.google_ad_width,c.google_ad_height,{callback:function(m,j){W(m,j,i)},pollingInterval:500,iframeAttrs:{style:"position: absolute;left:0px",marginWidth:"0",marginHeight:"0",vspace:"0",hspace:"0",allowTransparency:"true"},parentDivId:e})}else{a.write('<iframe name="google_ads_frame" width='+u(c.google_ad_width)+" height="+u(c.google_ad_height)+" frameborder="+u(c.google_ad_frameborder)+
" src="+u(b)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">');a.write("</iframe>")}if(d!=null){a.write("</div>")}}}else if(c.google_ad_output=="textlink"){a.write('<script language="JavaScript1.1" src='+u(b)+"><\/script>")}}function da(c){var a=null;c.google_ad_frameborder=a;c.google_ad_format=a;c.google_page_url=a;c.google_language=a;c.google_gl=a;c.google_country=a;c.google_region=a;c.google_city=a;c.google_hints=a;c.google_safe=a;c.google_encoding=
a;c.google_ad_output=a;c.google_max_num_ads=a;c.google_ad_channel=a;c.google_contents=a;c.google_alternate_ad_url=a;c.google_alternate_color=a;c.google_color_bg=a;c.google_color_text=a;c.google_color_link=a;c.google_color_url=a;c.google_color_border=a;c.google_color_line=a;c.google_reuse_colors=a;c.google_adtest=a;c.google_kw_type=a;c.google_kw=a;c.google_num_radlinks=a;c.google_max_radlink_len=a;c.google_rl_filtering=a;c.google_rl_mode=a;c.google_rt=a;c.google_rl_dest_url=a;c.google_num_radlinks_per_unit=
a;c.google_ad_type=a;c.google_image_size=a;c.google_feedback=a;c.google_skip=a;c.google_page_location=a;c.google_referrer_url=a;c.google_ad_region=a;c.google_ad_section=a;c.google_bid=a;c.google_cpa_choice=a;c.google_cust_age=a;c.google_cust_gender=a;c.google_cust_interests=a;c.google_cust_id=a;c.google_cust_job=a;c.google_cust_u_url=a;c.google_cust_l=a;c.google_cust_lh=a;c.google_cust_ch=a;c.google_ed=a;c.google_targeting=a;c.google_ad_host=a;c.google_ad_slot=a;c.google_ad_override=a;c.google_ui_features=
a;c.google_only_ads_with_video=a;c.google_disable_video_autoplay=a}function O(c){var a=null,b=window,d=document,e=new Date,f=e.getTime(),g=b.google_ad_format;if(b.google_cpa_choice!=a){b.google_ad_url="http://pagead2.googlesyndication.com/cpa/ads?";b.google_ad_url+="client="+escape(B(b.google_ad_client));b.google_ad_region="_google_cpa_region_";h("cpa_choice",b.google_cpa_choice);if(typeof d.characterSet!="undefined"){n("oe",d.characterSet)}else if(typeof d.charset!="undefined"){n("oe",d.charset)}}else{b.google_ad_url=
"http://pagead2.googlesyndication.com/pagead/ads?";b.google_ad_url+="client="+escape(B(b.google_ad_client))}h("host",b.google_ad_host);var i=b.google_num_slots_by_client,m=b.google_num_slots_by_channel,j=b.google_prev_ad_formats_by_region,l=b.google_prev_ad_slotnames_by_region;if(b.google_ad_region==a&&b.google_ad_section!=a){b.google_ad_region=b.google_ad_section}var k=b.google_ad_region==a?"":b.google_ad_region,o=false;if(g){o=g.indexOf("_0ads")>0}else if(b.google_ad_output!="html"&&b.google_num_radlinks>
0){o=true}if(o){if(b.google_num_0ad_slots){b.google_num_0ad_slots=b.google_num_0ad_slots+1}else{b.google_num_0ad_slots=1}if(b.google_num_0ad_slots>3){return false}}else if(b.google_cpa_choice==a){if(b.google_num_ad_slots){b.google_num_ad_slots=b.google_num_ad_slots+1}else{b.google_num_ad_slots=1}if(b.google_num_slots_to_rotate){j[k]=a;l[k]=a;if(b.google_num_slot_to_show==a){b.google_num_slot_to_show=f%b.google_num_slots_to_rotate+1}if(b.google_num_slot_to_show!=b.google_num_ad_slots){return false}}else if(b.google_num_ad_slots>
6&&k==""){return false}}h("dt",e.getTime());h("hl",b.google_language);if(b.google_country){h("gl",b.google_country)}else{h("gl",b.google_gl)}h("gr",b.google_region);n("gcs",b.google_city);n("hints",b.google_hints);h("adsafe",b.google_safe);h("oe",b.google_encoding);h("lmt",b.google_last_modified_time);n("alternate_ad_url",b.google_alternate_ad_url);h("alt_color",b.google_alternate_color);h("skip",b.google_skip);h("targeting",b.google_targeting);var p=b.google_ad_client;if(!i[p]){i[p]=1;i.length+=
1}else{i[p]+=1}if(j[k]){n("prev_fmts",j[k].toLowerCase());if(i.length>1){h("slot",i[p])}}if(l[k]){n("prev_slotnames",l[k].toLowerCase())}if(g&&!b.google_ad_slot){n("format",g.toLowerCase());if(j[k]){j[k]=j[k]+","+g}else{j[k]=g}}if(b.google_ad_slot){if(l[k]){l[k]=l[k]+","+b.google_ad_slot}else{l[k]=b.google_ad_slot}}h("num_ads",b.google_max_num_ads);h("output",c!=a?c:b.google_ad_output);h("adtest",b.google_adtest);if(b.google_ad_slot){h("slotname",b.google_ad_slot)}n("correlator",b.google_correlator);
if(b.google_ad_channel){var z=b.google_ad_channel;n("channel",z);var s="",t=z.split("+");for(var q=0;q<t.length;q++){var r=t[q];if(!m[r]){m[r]=1}else{s+=r+"+"}}n("pv_ch",s)}n("url",b.google_page_url);v("bg",b.google_color_bg,f);v("text",b.google_color_text,f);v("link",b.google_color_link,f);v("url",b.google_color_url,f);v("border",b.google_color_border,f);v("line",b.google_color_line,f);if(b.google_reuse_colors)h("reuse_colors",1);else h("reuse_colors",0);h("kw_type",b.google_kw_type);n("kw",b.google_kw);
n("contents",b.google_contents);h("num_radlinks",b.google_num_radlinks);h("max_radlink_len",b.google_max_radlink_len);h("rl_filtering",b.google_rl_filtering);h("rl_mode",b.google_rl_mode);h("rt",b.google_rt);n("rl_dest_url",b.google_rl_dest_url);h("num_radlinks_per_unit",b.google_num_radlinks_per_unit);h("ad_type",b.google_ad_type);h("image_size",b.google_image_size);h("region",b.google_ad_region);h("feedback_link",b.google_feedback);n("ref",b.google_referrer_url);n("loc",b.google_page_location);
h("bid",b.google_bid);h("cust_age",b.google_cust_age);h("cust_gender",b.google_cust_gender);h("cust_interests",b.google_cust_interests);h("cust_id",b.google_cust_id);h("cust_job",b.google_cust_job);h("cust_u_url",b.google_cust_u_url);h("cust_l",b.google_cust_l);h("cust_lh",b.google_cust_lh);h("cust_ch",b.google_cust_ch);h("ed",b.google_ed);n("ui",b.google_ui_features);n("only_ads_with_video",b.google_only_ads_with_video);n("disable_video_autoplay",b.google_disable_video_autoplay);if(M(b,d)&&d.body){var w=
d.body.scrollHeight,A=d.body.clientHeight;if(A&&w){n("cc",Math.round(A*100/w))}}T();h("ga_vid",b.gaGlobal.vid);h("ga_sid",b.gaGlobal.sid);h("ga_hid",b.gaGlobal.hid);h("ga_fc",b.gaGlobal.from_cookie);n("ga_wpids",b.google_analytics_webpropids);h("google_ad_override",b.google_ad_override);h("flash",b.google_flash_version);V(b,e);return true}function N(){var c=window,a=document,b=false;if(X(c.google_ad_output,c.google_ad_client)&&!ga()){b=true}var d=b?"json_html":null;if(!O(d)){return}if(!b){ha(c,a,
c.google_ad_url,null)}else{ca()}da(c)}function S(c,a,b){N();return true}function M(c,a){return c.top.location==a.location}function L(c,a){var b=a.documentElement;if(M(c,a))return false;if(c.google_ad_width&&c.google_ad_height){var d=1,e=1;if(c.innerHeight){d=c.innerWidth;e=c.innerHeight}else if(b&&b.clientHeight){d=b.clientWidth;e=b.clientHeight}else if(a.body){d=a.body.clientWidth;e=a.body.clientHeight}if(e>2*c.google_ad_height||d>2*c.google_ad_width){return false}}return true}function Z(c){var a=
window,b=document,d=b.location,e=b.referrer,f=null,g=a.onerror;a.onerror=c;if(a.google_ad_frameborder==f){a.google_ad_frameborder=0}if(a.google_ad_output==f){a.google_ad_output="html"}if(a.google_ad_format==f&&a.google_ad_output=="html"){a.google_ad_format=a.google_ad_width+"x"+a.google_ad_height}if(a.google_page_url==f){a.google_page_url=e;if(!L(a,b)){a.google_page_url=d;a.google_last_modified_time=Date.parse(b.lastModified)/1000;a.google_referrer_url=e}}else{a.google_page_location=e;if(!L(a,b)){a.google_page_location=
d}}if(a.google_num_slots_by_channel==f){a.google_num_slots_by_channel=[]}if(a.google_num_slots_by_client==f){a.google_num_slots_by_client=[]}if(a.google_prev_ad_formats_by_region==f){a.google_prev_ad_formats_by_region=[]}if(a.google_prev_ad_slotnames_by_region==f){a.google_prev_ad_slotnames_by_region=[]}if(a.google_correlator==f){a.google_correlator=(new Date).getTime()}if(a.google_adslot_loaded==f){a.google_adslot_loaded={}}if(a.google_adContentsBySlot==f){a.google_adContentsBySlot={}}if(a.google_flash_version==
f){a.google_flash_version=P().toString()}a.onerror=g}function y(c){if(c in C){return C[c]}return C[c]=navigator.userAgent.toLowerCase().indexOf(c)!=-1}var C={};function D(){return y("msie")&&!window.opera}function F(){return y("safari")}function U(){var c=navigator.userAgent,a=c.indexOf("MSIE ");if(a==-1){return 0}else{return parseFloat(c.substring(a+5,c.indexOf(";",a)))}}function ga(){if(D()){var c=U();return c<=5}else if(y("firefox")){var a=navigator.userAgent.indexOf("Firefox")+8,b=parseInt(navigator.userAgent.charAt(a)),
d=navigator.userAgent.slice(a);return b<1}else if(F()){var a=navigator.userAgent.indexOf("Safari")+7,d=navigator.userAgent.slice(a),e=parseInt(d);return e<412}else if(window.opera!=null){var a=navigator.userAgent.indexOf("Opera")+6,d=navigator.userAgent.slice(a),b=parseInt(d);return b<9}else if(!D()&&!F()&&y("mozilla")){var a=navigator.userAgent.indexOf("Netscape")+9,d=navigator.userAgent.slice(a),b=parseInt(d);return b<7}else{return true}}function X(c,a){var b=window;if(c!="html"){return false}if(b.google_cpa_choice!=
null){return false}var d={};d["ca-pub-8954402009499768"]=true;d["ca-pub-8091322912406003"]=true;d["ca-pub-2996719119399840"]=true;d["ca-pub-8887131281660947"]=true;d["ca-pub-0636374063477327"]=true;d["ca-pub-9500441424288493"]=true;d["ca-pub-6682766817737063"]=true;d["ca-pub-3645353514626463"]=true;d["ca-pub-7027491298716603"]=true;d["ca-pub-2071992140100640"]=true;d["ca-pub-4840216691262122"]=true;d["ca-pub-9425162160615080"]=true;d["ca-pub-6655028338425523"]=true;d["ca-pub-7869439110764952"]=true;
return d[B(a)]!=null}function Y(c,a){if(c!="html"){return false}var b={};b["ca-pub-8344185808443527"]=true;return b[B(a)]!=null}function ca(){var c=window;h("impl","s");h("callback","_google_setAdContentsBySlotForSync");document.write("<script src = '"+c.google_ad_url+"'><\/script>")}function ea(c){var a=document.getElementById("google_flash_div");if(a!=null){a.style.height=c+"px"}var b=document.getElementById("google_flash_obj");if(b!=null){b.height=c}var d=document.getElementById("google_flash_embed");
if(d!=null){d.height=c}}window.google_createDivWithContent=function(c){var a=window,b="google_ads_div_"+c,d="<div id="+b+">",e=a.google_adContentsBySlot[c];if(e==null){return}d+=e._html_;d+="\n</div>\n";document.write(d)};window.google_createDOMIframe=function(c,a,b,d){var e=document.getElementsByTagName("script"),f=e[e.length-1],g=document.createElement("iframe");g.id="google_ads_iframe_"+c;g.width=a;g.height=b;g.vspace=0;g.hspace=0;g.allowTransparency="true";g.scrolling="no";g.marginWidth=0;g.marginHeight=
0;g.frameBorder=0;g.style.border=0;f.parentNode.appendChild(g);g.contentWindow.document.write(d);g.contentWindow.document.close()};window.google_createiframe=function(c,a,b,d,e){var f="google_ads_div_"+c,g="google_ads_iframe_"+c,i="<div id="+f+">";i+="<iframe id="+g+' width="'+d+'" height="'+e+'" vspace="0" hspace="0" allowtransparency="true" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" style="border:0px;" src="'+a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,
"&quot;")+'"';i+=' onload="'+b+'"';i+="></iframe></div>";document.write(i)};var G="google_ads_iframe_".length;function K(c){var a=c.getAttribute("id"),b=a.substr(G,a.length-G);return b}function $(c){var a=window,b=K(c),d=a.google_adslot_loaded[b];if(d){return}a.google_adslot_loaded[b]=true;var e=window.google_adContentsBySlot[b],f=c.contentWindow?c.contentWindow.document:c.contentDocument;if(f==null){if(document.implementation&&document.implementation.createDocument){f=document.implementation.createDocument("",
b,null)}else if(typeof ActiveXObject!=undefined){f=new ActiveXObject("Msxml.DOMDocument")}else{return}}f.open("text/html","replace");f.write(e._html_);f.close()}window._google_syncAdSlotLoaded=function(c){var a=K(c);$(c)};window._google_setAdContentsBySlotForSync=function(c){var a=window;for(var b in c){var d=c[b];a.google_adContentsBySlot[b]=d;if(d==null||d._empty_){}else if(d._expandable_){a.google_createDivWithContent(b)}else{if(navigator.userAgent.indexOf("MSIE ")>0){a.google_adslot_loaded[b]=
false;var e="window._google_syncAdSlotLoaded(this);";a.google_createiframe(b,"about:blank",e,d._width_,d._height_)}else{a.google_createDOMIframe(b,d._width_,d._height_,d._html_)}}}};function ba(c){var a={},b=c.split("?"),d=b[b.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0]){try{a[f[0].toLowerCase()]=f.length>1?(window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1])):""}catch(g){}}}return a}function aa(){var c=window,a=ba(document.URL);
if(a.google_ad_override){c.google_ad_override=a.google_ad_override}}function P(){var c=0;if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description){c=a.description.replace(/([a-zA-Z]|\s)+/,"").split(".")[0]}}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){c=3;var b=1;while(b){try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(c+1));c++}catch(d){b=null}}}else if(D()){try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){try{var b=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");c=6;b.AllowScriptAccess="always"}catch(d){if(c==6){return c}}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(b!=null){c=b.GetVariable("$version").split(" ")[1].split(",")[0]}}return c}window.google_resize_flash_ad=ea;aa();Z(S);N();
})()